# Generated by Django 4.2.5 on 2023-10-26 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_Deposito', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('imagen', models.ImageField(upload_to='firma_imagenes/')),
            ],
        ),
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_Laboratorio', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_Medicamento', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecepcionMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_invima', models.TextField()),
                ('lote', models.TextField()),
                ('cantidad', models.IntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('cumple_norma', models.BooleanField(default=True)),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acta.laboratorio')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acta.medicamento')),
            ],
        ),
        migrations.CreateModel(
            name='ActaRecepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('factura', models.TextField()),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acta.deposito')),
                ('firma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Acta.firma')),
                ('recepcion_medicamentos', models.ManyToManyField(to='Acta.recepcionmedicamento')),
            ],
        ),
    ]
